# Generated by Django 2.2.10 on 2020-04-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(verbose_name='Data/Hora da Resposta')),
                ('posicao', models.CharField(max_length=255, verbose_name='Posição')),
                ('campus', models.CharField(max_length=150, verbose_name='Campus')),
                ('nivel_curso', models.CharField(max_length=150, verbose_name='Nível Curso')),
                ('auxilio', models.CharField(max_length=3, verbose_name='Auxílio')),
                ('avaliacao_moodle', models.PositiveIntegerField(verbose_name='Avaliação Moodle')),
                ('avaliacao_conteudo', models.PositiveIntegerField(verbose_name='Avaliação Conteúdo do Professor')),
                ('avaliacao_orientacoes', models.PositiveIntegerField(verbose_name='Avaliação Orientações do Professor')),
                ('acesso_internet', models.CharField(max_length=255, verbose_name='Acesso à Internet')),
                ('deficiencia', models.CharField(max_length=150, verbose_name='Deficiência Física')),
                ('transtorno', models.CharField(max_length=150, verbose_name='Transtorno de Aprendizagem ou Desenvolvimento')),
                ('possui_pc', models.CharField(blank=True, max_length=3, null=True, verbose_name='PC ou Notebook')),
                ('possui_celular', models.CharField(blank=True, max_length=3, null=True, verbose_name='Celular Smartphone')),
                ('possui_tablet', models.CharField(blank=True, max_length=3, null=True, verbose_name='Tablet')),
                ('possui_tv', models.CharField(blank=True, max_length=3, null=True, verbose_name='Smart TV')),
            ],
            options={
                'verbose_name': 'Resposta do Aluno',
                'verbose_name_plural': 'Respostas dos Alunos',
                'ordering': ['campus', 'nivel_curso'],
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da Resposta')),
                ('opiniao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Opinião Atividades Remotas')),
                ('posicao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Posição')),
                ('campus', models.CharField(blank=True, max_length=150, null=True, verbose_name='Campus')),
                ('acesso_internet', models.CharField(blank=True, max_length=255, null=True, verbose_name='Acesso à Internet')),
                ('promovendo_ar', models.CharField(blank=True, max_length=3, null=True, verbose_name='Promovendo Atividades Remotas')),
                ('competencia_avaliacao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Avaliação online')),
                ('competencia_desenvolvimento', models.CharField(blank=True, max_length=150, null=True, verbose_name='Desenvolvimento de Objetos de Aprendizagem')),
                ('competencia_design', models.CharField(blank=True, max_length=150, null=True, verbose_name='Design Educacional (Instrucional)')),
                ('competencia_elaboracao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Elaboração de Projeto Pedagógico de Curso para EAD')),
                ('competencia_ensino', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ensino Híbrido')),
                ('competencia_plataforma', models.CharField(blank=True, max_length=150, null=True, verbose_name='Plataforma Moodle ')),
                ('competencia_producao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Produção de livro-texto')),
                ('competencia_roteiro', models.CharField(blank=True, max_length=150, null=True, verbose_name='Roteiro para vídeo aulas')),
                ('competencia_sala', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sala de aula invertida')),
                ('competencia_simulador', models.CharField(blank=True, max_length=150, null=True, verbose_name='Simuladores e Ambientes de Imersão')),
                ('competencia_rnp', models.CharField(blank=True, max_length=150, null=True, verbose_name='WebConferência RNP')),
                ('avaliacao_experiencia', models.PositiveIntegerField(blank=True, null=True, verbose_name='Avaliação Experiência')),
                ('possui_pc', models.CharField(blank=True, max_length=3, null=True, verbose_name='PC ou Notebook')),
                ('possui_celular', models.CharField(blank=True, max_length=3, null=True, verbose_name='Celular Smartphone')),
                ('possui_tablet', models.CharField(blank=True, max_length=3, null=True, verbose_name='Tablet')),
                ('possui_tv', models.CharField(blank=True, max_length=3, null=True, verbose_name='Smart TV')),
            ],
        ),
        migrations.CreateModel(
            name='Tae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da Resposta')),
                ('opiniao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Opinião Atividades Remotas')),
                ('posicao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Posição')),
                ('campus', models.CharField(blank=True, max_length=150, null=True, verbose_name='Campus')),
                ('acesso_internet', models.CharField(blank=True, max_length=255, null=True, verbose_name='Acesso à Internet')),
                ('formacao_ead', models.CharField(blank=True, max_length=3, null=True, verbose_name='Formação em EaD')),
                ('competencia_avaliacao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Avaliação online')),
                ('competencia_desenvolvimento', models.CharField(blank=True, max_length=150, null=True, verbose_name='Desenvolvimento de Objetos de Aprendizagem')),
                ('competencia_design', models.CharField(blank=True, max_length=150, null=True, verbose_name='Design Educacional (Instrucional)')),
                ('competencia_elaboracao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Elaboração de Projeto Pedagógico de Curso para EAD')),
                ('competencia_ensino', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ensino Híbrido')),
                ('competencia_plataforma', models.CharField(blank=True, max_length=150, null=True, verbose_name='Plataforma Moodle ')),
                ('competencia_producao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Produção de livro-texto')),
                ('competencia_roteiro', models.CharField(blank=True, max_length=150, null=True, verbose_name='Roteiro para vídeo aulas')),
                ('competencia_sala', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sala de aula invertida')),
                ('competencia_simulador', models.CharField(blank=True, max_length=150, null=True, verbose_name='Simuladores e Ambientes de Imersão')),
                ('competencia_rnp', models.CharField(blank=True, max_length=150, null=True, verbose_name='WebConferência RNP')),
                ('avaliacao_jornada', models.PositiveIntegerField(blank=True, null=True, verbose_name='Avaliação Jornada em Casa')),
                ('avaliacao_producao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Avaliação Produção')),
                ('possui_pc', models.CharField(blank=True, max_length=3, null=True, verbose_name='PC ou Notebook')),
                ('possui_celular', models.CharField(blank=True, max_length=3, null=True, verbose_name='Celular Smartphone')),
                ('possui_tablet', models.CharField(blank=True, max_length=3, null=True, verbose_name='Tablet')),
                ('possui_tv', models.CharField(blank=True, max_length=3, null=True, verbose_name='Smart TV')),
            ],
        ),
    ]
