# Generated by Django 2.2.10 on 2020-05-11 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20200407_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da Resposta')),
                ('nivel_curso', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nível Curso')),
                ('periodo_letivo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Período Letivo')),
                ('campus', models.CharField(blank=True, max_length=150, null=True, verbose_name='Campus')),
                ('acesso_internet', models.CharField(blank=True, max_length=255, null=True, verbose_name='Acesso à Internet')),
                ('possui_pc', models.CharField(blank=True, max_length=3, null=True, verbose_name='PC ou Notebook')),
                ('possui_celular', models.CharField(blank=True, max_length=3, null=True, verbose_name='Celular Smartphone')),
                ('possui_tablet', models.CharField(blank=True, max_length=3, null=True, verbose_name='Tablet')),
                ('possui_tv', models.CharField(blank=True, max_length=3, null=True, verbose_name='Smart TV')),
                ('auxilio', models.CharField(blank=True, max_length=3, null=True, verbose_name='Auxílio')),
                ('avaliacao_conteudo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Avaliação Conteúdo do Professor')),
                ('avaliacao_orientacoes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Avaliação Orientações do Professor')),
                ('avaliacao_comunicacao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Avaliação Comunicação do Professor')),
                ('horas_estudo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Horas de Estudo por Dia')),
                ('avaliacao_ar', models.PositiveIntegerField(blank=True, null=True, verbose_name='Avaliação Atividades Remotas')),
                ('posicao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Posição')),
            ],
            options={
                'verbose_name': 'Resposta do Aluno 2',
                'verbose_name_plural': 'Respostas dos Alunos 2',
                'ordering': ['-data_resposta', 'campus', 'nivel_curso'],
            },
        ),
        migrations.CreateModel(
            name='Docente2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da Resposta')),
                ('campus', models.CharField(blank=True, max_length=150, null=True, verbose_name='Campus')),
                ('promovendo_ar', models.CharField(blank=True, max_length=3, null=True, verbose_name='Promovendo Atividades Remotas')),
                ('avaliacao_ar', models.PositiveIntegerField(blank=True, null=True, verbose_name='Avaliação Atividades Remotas')),
                ('avaliacao_comunicao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Avaliação Comunicação com Alunos')),
                ('avaliacao_participacao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Avaliação Participação Alunos')),
                ('posicao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Posição')),
                ('sugestao_suspensao', models.TextField(blank=True, null=True, verbose_name='Sugestão Atividades Suspensão')),
                ('sugestao_capacitacao', models.TextField(blank=True, null=True, verbose_name='Sugestão Capacitação')),
            ],
            options={
                'verbose_name': 'Resposta do Docente 2',
                'verbose_name_plural': 'Respostas dos Docentes 2',
                'ordering': ['-data_resposta', 'campus'],
            },
        ),
        migrations.CreateModel(
            name='Tae2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da Resposta')),
                ('campus', models.CharField(blank=True, max_length=150, null=True, verbose_name='Campus')),
                ('setor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Setor Lotação')),
                ('avaliacao_producao', models.CharField(blank=True, max_length=15, null=True, verbose_name='Avaliação Produção')),
                ('avaliacao_rendimento', models.PositiveIntegerField(blank=True, null=True, verbose_name='Avaliação Rendimento')),
                ('posicao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Posição')),
                ('sugestao_suspensao', models.TextField(blank=True, null=True, verbose_name='Sugestão Atividades Suspensão')),
                ('sugestao_capacitacao', models.TextField(blank=True, null=True, verbose_name='Sugestão Capacitação')),
            ],
            options={
                'verbose_name': 'Resposta do TAE 2',
                'verbose_name_plural': 'Respostas dos TAEs 2',
                'ordering': ['-data_resposta', 'campus'],
            },
        ),
        migrations.CreateModel(
            name='GrupoRisco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Grupo de Risco')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Aluno2')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Docente2')),
                ('tae', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Tae2')),
            ],
        ),
        migrations.CreateModel(
            name='DificuldadeCasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificuldade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dificuldade')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Aluno2')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Docente2')),
                ('tae', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Tae2')),
            ],
        ),
    ]
