# Generated by Django 2.2.10 on 2020-05-11 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_aluno2_dificuldadecasa_docente2_gruporisco_tae2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocenteReitoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da Resposta')),
                ('campus', models.CharField(blank=True, max_length=150, null=True, verbose_name='Campus')),
                ('setor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Setor Lotação')),
                ('avaliacao_producao', models.CharField(blank=True, max_length=15, null=True, verbose_name='Avaliação Produção')),
                ('avaliacao_rendimento', models.PositiveIntegerField(blank=True, null=True, verbose_name='Avaliação Rendimento')),
                ('posicao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Posição')),
                ('sugestao_suspensao', models.TextField(blank=True, null=True, verbose_name='Sugestão Atividades Suspensão')),
                ('sugestao_capacitacao', models.TextField(blank=True, null=True, verbose_name='Sugestão Capacitação')),
            ],
            options={
                'verbose_name': 'Resposta do Docente na Reitoria 2',
                'verbose_name_plural': 'Respostas dos Docentes na Reitoria 2',
                'ordering': ['-data_resposta', 'campus'],
            },
        ),
        migrations.AddField(
            model_name='dificuldadecasa',
            name='docente_reitoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.DocenteReitoria'),
        ),
        migrations.AddField(
            model_name='gruporisco',
            name='docente_reitoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.DocenteReitoria'),
        ),
    ]
