# Generated by Django 2.2.10 on 2020-05-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20200511_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno2',
            name='periodo_letivo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Período Letivo'),
        ),
    ]
